name: Autotest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:2.5
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: password
        volumes:
          - /var/run/mysqld/mysqld.sock:/var/lib/mysql
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=3
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
    - uses: actions/checkout@master
    - name: bundler install
      run: gem install bundler -v 2.0.1
    - name: build
      run: bundle install
    - name: create
      run: RAILS_ENV=test bundle exec rake db:create
      env:
       DATABASE_URL: mysql2://test:test@mysql
    - name: migrate
      run: RAILS_ENV=test bundle exec rake db:migrate
      env:
       DATABASE_URL: mysql2://test:test@mysql
    - name: autorun rspec tests
      run: bundle exec rspec spec
