name: Autotest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:2.5
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: password
        volumes:
          - /var/run/mysqld/mysqld.sock:/var/lib/mysql
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=3
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
    - uses: actions/checkout@master
    - name: cat etc host
      run: cat /etc/hosts
    - name: cat etc resolv
      run: cat /etc/resolv.conf
