name: Autotest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: password
        volumes:
          - /var/run/mysqld/mysqld.sock:/var/lib/mysql
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=3
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
    - uses: actions/checkout@master
    - name: netinstall
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y net-tools
    - name: net_pre
      run: netstat -a
    - name: Verify MySQL connection from container
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql --host mysql -uroot -ppassword -e "SHOW DATABASES"
    - name: net
      run: netstat -a
    - name: net2
      run: echo ${{ job.services.mysql.ports['3306'] }}
