name: Autotest

on: [push]

jobs:
  test:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: password
        volumes:
          - /var/lib/mysql/mysql.sock:/var/lib/mysql/mysql.sock
        ports:
          - 3306/tcp
      redis:
        image: redis
        ports:
          - 6379/tcp
      rails:
        image: ruby:2.5
        volumes:
          - /var/lib/mysql/mysql.sock:/var/run/mysqld/mysqld.sock
		runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install bundler
      run: gem install bundler -v 2.0.1